### ISSUE TITLE
Observing Pure Functional Components

### ISSUE THREAD

**Issue by c0d3ster** [jscottsmith/react-observed#3]
Does using this library on a component require that the component maintains it's own state?  I have a stateless component that I would like to observe, but stateless components can not use the ref property.  Is there any way around this besides converting my class syntax?

**Comment by jscottsmith** [comment]
The IntersectionObserver must be observing a DOM element, not a component. Refs attached to classes reference the component instance. 

To observe a component you could do this:

```jsx
// MyComponent takes the mapRef function and attaches it to a DOM element

const MyComponent = ({ mapRef, isInView }) => (
    <div ref={mapRef}>
        {isInView ? (
            <span>I'm observed and in view!</span>
        ) : (
            <span>I'm observed and not in view.</span>
        )}
    </div>
);

// Gets the mapRef function from the Observed render function and passes it as a prop to MyComponent

const ObservedComponent = () => (
    <Observed>
        {({ isInView, mapRef }) => (
            <MyComponent isInView={isInView} mapRef={mapRef} />
        )}
    </Observed>
);
``` 
I'll work on clarifying this in the README.

**Comment by c0d3ster** [comment]
I see, how does the Observed component know to rerender once the the isInView value changes?  My component is only rendering once and not updating after that.

**Comment by jscottsmith** [comment]
Internally it manages its own state and flips the isInView Boolean when conditions are met. Check out the [source](https://github.com/jscottsmith/react-observed/blob/master/src/Observed.js) to get a better sense.

If you're having trouble send me some code and I can take a look.

**Comment by c0d3ster** [comment]
as soon as I add a custom class to the observed div with the ref attribute, the component stops making updates and only renders once.  If I remove the class, the observed div simply becomes a 0 height element and the observed functionality works as it should.   I can share the link to my repo for you to take a look at it.

**Comment by jscottsmith** [comment]
Send a link, I'll take a look.

**Comment by c0d3ster** [comment]
It's on my profile actually, no readme yet but should be able to just pull in the code from my github and call npm start for port 8080

**Comment by jscottsmith** [comment]
Ah I see, the `intersectionRatio` of `0.45` is never being met because the default `options.threshold` is `1`. You'll need to provide the custom intersection options, the following should work for your use case:

```jsx
<Observed
    intersectionRatio={0.5}
    options={{
        root: null,
        rootMargin: '0px',
        threshold: [0, 0.25, 0.5, 0.75, 1],
    }}
>
```
Side note: the package.json in your repo is specifying React Router v4, but the code your using in the app is from the v3 API. Might want to update that as it causes errors in the app on a fresh install.

**Comment by c0d3ster** [comment]
I'm working on upgrading to v4 syntax now, thanks!  Also, it won't always not render the header it simply doesn't update when I scroll.  If you scroll to where the section is in view more than 50%, it will render the Header but it will never go away when you scroll away.

**Comment by jscottsmith** [comment]
The options I posted above seemed to work fine for me; scroll down header pops up, scroll back to top and the header disappears.

This doesn't work for you?

```jsx
const SectionContainer = ({ title, navList, children }) => (
  <Observed
    intersectionRatio={0.5}
    options={{
      root: null,
      rootMargin: '0px',
      threshold: [0, 0.25, 0.5, 0.75, 1],
    }}
  >
    {({ isInView, mapRef }) => (
      <div ref={mapRef} className="section-container">
        {isInView ? (
          <Header title={title} navList={navList} />
        ) : (
          <div>{isInView}</div>
        )}
        <div className="section-content">{children}</div>
      </div>
    )}
  </Observed>
);
```

**Comment by c0d3ster** [comment]
hmm I seemed to misunderstand some of the settings for the repo.  I found that the settings below gave me the best results for when I add another Section.  It's not perfect, but I think it'll be good with a bit of Tweening in there.
  <Observed 
    intersectionRatio={.44}
    options={{
      root: null,
      rootMargin: '0px',
      threshold: [.22, .66],
    }}
    >
